### PR TITLE
fix lepton indices (+veto condition), added modified tight-tight Z/g veto

### PR DESCRIPTION
**Pull request by mmarionncern**
As discussed in the past hours : 
- fixed tight leptons indices
  -kept the full list of tight leptons and defined a temporary list of indices not stored in the trees for 2lss
- added the veto condition when determining the indices
- added the tight-tight dilepton masses 

@gpetruc @cbotta @peruzzim @cheiddegg , if you think it is done in a improper way, let me know

### CODE REVIEW

**Comment by cbotta** [comment]
Hello @mmarionncern, @gpetruc  @peruzzim @cheiddegg 
few comments:
- we don't need these variables right?  L119-121
- in computing the indexes I would leave iL,iLp,iLT,iLTp with the same meaning as before, and add iLTv, iLTvp. In this way we have both ways inplemented

**Comment by mmarionncern** [comment]
@cbotta (and @gpetruc @peruzzim @cheiddegg )

The TT masses could be useful for a quick debugging if we want to change wuickly the mass veto, I would keep them from now unless you have a strong concern on the disk space.

I added back the previous set of indices and kept the new ones

**Comment by gpetruc** [comment]
Ok.

I couldn't yet look in the code, but one important thing is that we should
try to avoid is expression with nested indices, i.e. in the form
LepGood_xyz[iA[iB]], they could confuse the code that deals eg with fake
rates.
It's ok to use them within the friend producer, but what we should write
out are always indices that go directly in the main collection.

Giovanni
Il 19-mag-2015 18:10, "mmarionncern" notifications@github.com ha scritto:

**Comment by mmarionncern** [comment]
The changes allows to use indices directly, without any nesting. In my mail I was refering that option as a temporary workaround till i fix it in the friend tree producer.

**Pull request merged**
